### PR TITLE
Fixes #856 and associated bugs

### LINKED ISSUE #856: [0.5.0] Navigation section error
Multiple errors occurring
When you create more than one nav menu:

1. Only the last one appears in the navbar
2. When you navigate to /admin/content/navigation it  goes to /admin/content/navigation/new so none of the menu maps appear for reorder or editing

### PR DESCRIPTION
**Pull request by brianhyder**

### CODE REVIEW

File: include/http/request_handler.js [hunk 1]
```diff
@@ -762,33 +762,32 @@ module.exports = function RequestHandlerModule(pb) {
...
         // If we need to grab a host redirect
         if (!siteObj && redirectHost && RequestHandler.sites[redirectHost]) {
             siteObj = RequestHandler.sites[redirectHost];
         }
+        this.siteObj = siteObj;
 
-        else if (!siteObj) {
+        //derive the localization. We do it here so that if the site isn't
+        //available we can still have one available when we error out
+        this.localizationService = this.deriveLocalization({ session: session });
```
Comment (brianhyder) [inline include/http/request_handler.js]: This change isn't part of the section stuff but a fix for ensuring that a site is limited to its assigned locales after the redirect changes went in.

File: include/service/cache_entity_service.js [hunk 2]
```diff
@@ -41,15 +41,24 @@ module.exports = function CacheEntityServiceModule(pb) {
...
+
+        this.objType = options.objType;
+        this.keyField = options.keyField;
         this.valueField = options.valueField ? options.valueField : null;
         this.site = options.site || GLOBAL_SITE;
-        this.onlyThisSite = options.onlyThisSite ? true : false;
-        this.timeout    = options.timeout || 0;
+        this.onlyThisSite = !!options.onlyThisSite;
+        this.timeout = options.timeout || 0;
+        this.type = 'Cache-'+this.site+'-'+this.onlyThisSite;
```
Comment (brianhyder) [inline include/service/cache_entity_service.js]: Allows for better logging to see what site the setting service is pulling from

File: include/service/db_entity_service.js [hunk 3]
```diff
@@ -35,17 +35,36 @@ module.exports = function DbEntityServiceModule(pb) {
...
-        this.keyField   = options.keyField;
+
+        this.objType = options.objType;
+        this.keyField = options.keyField;
         this.valueField = options.valueField ? options.valueField : null;
-        this.site       = options.site || GLOBAL_SITE;
-        this.onlyThisSite       = options.onlyThisSite ? true : false;
+        this.site = options.site || GLOBAL_SITE;
+        this.onlyThisSite = !!options.onlyThisSite;
+        this.type = 'DB-'+this.site+'-'+this.onlyThisSite;
```
Comment (brianhyder) [inline include/service/db_entity_service.js]: provides better logging to see what site is pulling from the setting service

File: include/service/entities/section_service.js [hunk 4]
```diff
@@ -320,7 +320,7 @@ module.exports = function SectionServiceModule(pb) {
                 for(var i = 0; i < sectionMap.length; i++) {
                     var section    = SectionService.getSectionData(sectionMap[i].uid, sections, currUrl);
                     if (util.isNullOrUndefined(section)) {
-                        pb.log.error('SectionService: The navigation map is out of sync.  Root [%s] could not be found.', sectionMap[i].uid);
+                        pb.log.error('SectionService: The navigation map is out of sync.  Root [%s] could not be found for site [%s].', sectionMap[i].uid, self.site);
```
Comment (brianhyder) [inline include/service/entities/section_service.js]: better logging to provide site context

File: include/service/entities/section_service.js [hunk 5]
```diff
@@ -462,7 +462,7 @@ module.exports = function SectionServiceModule(pb) {
             //validate for each type of nav item
             switch(navItem.type) {
             case 'container':
-                onDone(null, errors);
+                onDone(null, []);
```
Comment (brianhyder) [inline include/service/entities/section_service.js]: @cchatham This fixes the out of memory error.  When ```onDone``` is called it combines the errors in the ```errors``` variable with those where are passed into ```onDone``` as the second parameter.  It was adding errors to itself creating an infinite loop.

File: plugins/pencilblue/controllers/actions/admin/content/navigation/new_nav_item.js [hunk 6]
```diff
@@ -16,79 +16,186 @@
...
+
     /**
-     * Creates a nav item
+     * Persists a nav item
+     * @class PersistNavItemController
+     * @constructor
      */
-    function NewNavItem(){}
-    util.inherits(NewNavItem, BaseAdminController);
+    function PersistNavItemController(){}
```
Comment (brianhyder) [inline plugins/pencilblue/controllers/actions/admin/content/navigation/new_nav_item.js]: Combined new & edit functionality to reduce code and complexity
