### PR TITLE
Fixes #612. Corrects issues where the cache entity service was not pr…

### LINKED ISSUE #612: Compatibility issue with Redis Labs
Given the fact that [Redis Labs only allows one database](https://support.redislabs.com/hc/en-us/articles/202215763-Can-I-have-multiple-databases-on-my-Redis-DB-Getting-ERR-invalid-DB-index-), instead of multiple numbered databases, PencilBlue currently fails to connect successfully to Redis Labs.

I found that `redis_registration_provider.js` specifies a Redis database index of `2`, on line 46. RedisLabs only allows an index of `0`, and I found that if I change that to `0` then I seem to be able to use PencilBlue with a Redis Labs database. However I'm worried about what the implications of changing the registry database index are. Does PencilBlue need more than one Redis database in order to work correctly?

### PR DESCRIPTION
**Pull request by brianhyder**
…operly serializing and deserializing values.

Plugin & theme settings now properly cache too.

### CODE REVIEW

File: include/service/cache_entity_service.js [hunk 1]
```diff
@@ -52,16 +55,14 @@ module.exports = function CacheEntityServiceModule(pb) {
     CacheEntityService.prototype.get = function(key, cb){
 
         var self = this;
-        pb.cache.get(key, function(err, result){
+        pb.cache.get(key, function(err, result){console.log(util.inspect(result));
```
Comment (markbaird) [inline include/service/cache_entity_service.js]: Did you intend to commit this console.log()?

File: include/service/cache_entity_service.js [hunk 2]
```diff
@@ -110,10 +122,10 @@ module.exports = function CacheEntityServiceModule(pb) {
                 }
                 rawVal[self.valueField] = value;
                 val                     = JSON.stringify(rawVal);
-            }
+            }console.log('TIMEOUT: '+self.timeout);
```
Comment (markbaird) [inline include/service/cache_entity_service.js]: Also this one

File: include/service/cache_entity_service.js (hunk 1 above)
Comment (brianhyder) [inline include/service/cache_entity_service.js]: Fail... No, I thought I got them all. Thank you for the heads up.
