### PR TITLE
Fixes #1058 - Corrects an issue that prevents image metadata from being populated

### LINKED ISSUE #1058: SEO meta_thumbnail never gets populated when viewing article.
**Description:**
<meta property="og:image" content="^meta_thumbnail^">
^meta_thumbnail^ will never be populated due to a function getMetaInfo in ContentObjectService returning an object instead returning the first object of an array.

/include/service/entities/content/content_object_service.js
ContentObjectService.prototype.getMetaInfo
Line: 465 
callback(err, util.isNullOrUndefined(media) ? '' : media.location);
the media returned is an array not an object. media[0].location will return the correct thumbnail data.

**Steps to Reproduce:**
Fill an article with SEO and choose a thumbnail. Inspect the article in your browser on the head section. 
<meta property="og:image" content=""> Image meta property is blank.

**Configuration Details:**

**Log Output:**

PencilBlue Version:  0.5.1

Node.js Version: 5.5.0

Environment Description: OS X 10.11.5 Google Chrome

### PR DESCRIPTION
**Pull request by brianhyder**
Fixes #1058 

- [x] Unit tests created and pass
- [x] JS Docs have been updated

**Description:**
Corrects an issue that prevented the thumbnail metadata from populating in templates.  The code was calling the incorrect method on the MediaService

@pencilblue/owners

### CODE REVIEW

File: include/service/entities/article_service.js [hunk 1]
```diff
@@ -155,7 +155,7 @@ module.exports = function(pb) {
             order = options.order;
         }
         else {
-            order = [{'publish_date': pb.DAO.DESC}, {'created': pb.DAO.DESC}];
+            order = [['publish_date', pb.DAO.DESC], ['created', pb.DAO.DESC]];
```
Comment (brianhyder) [inline include/service/entities/article_service.js]: corrected this bug that was left over from where we updated the mongo driver

File: include/service/entities/content/content_object_service.js [hunk 2]
```diff
@@ -456,12 +456,16 @@ module.exports = function(pb) {
...
+                        isFile: 1
                     },
                     where: pb.DAO.getIdWhere(content.thumbnail)
                 };
                 var mediaService = new pb.MediaServiceV2({ site: self.site, onlyThisSite: self.onlyThisSite });
-                mediaService.getAll(mOpts, function(err, media) {
+                mediaService.getSingle(mOpts, function(err, media) {
+                    if (media.isFile) {
+                        media.location = pb.UrlService.createSystemUrl(media.location)
+                    }
```
Comment (brianhyder) [inline include/service/entities/content/content_object_service.js]: the if block will ensure that uploaded files will emit with the full system URL (site root + path)
